sudo: required
language: python

# which python versions to test
python:
  - "3.5"
  - "3.6"

# Enable 3.7 without globally enabling 'dist: xenial' for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial

# Cache directory $HOME/.cache/pip
cache: pip

# command before installation: upgrade pip, remove old sympde installation
before_install:
  - python -m pip install --upgrade pip
  - python -m pip uninstall -y sympde
  
# command to install project and its dependencies
install:
  - python -m pip install .

# command to run tests
script:
  - python -m pytest sympde
