[build-system]
requires = ["setuptools >= 77.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name            = "sympde"
version         = "0.20.0"
description     = "Symbolic calculus for partial differential equations (and variational forms)"
readme          = "README.rst"
requires-python = ">= 3.9"
license         = "MIT"
license-files   = ["LICENSE"]
authors         = [{name = "Ahmed Ratnani", email = "ratnaniahmed@gmail.com"}]
maintainers = [
    {name = "Yaman Güçlü", email = "yaman.guclu@gmail.com"},
    {name = "Said Hadjout"},
]
keywords     = ["finite elements", "partial differential equations", "symbolic mathematics"]
classifiers  = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = [
    'sympy >= 1.5, < 1.10',
    'h5py',
    'pyyaml',
    'numpy',
    'matplotlib'
]

[project.optional-dependencies]
test = [
    "pytest >= 8",
    "pytest-cov >= 5",
    "pytest-xdist >= 3",
]

[project.urls]
Issues = "https://github.com/pyccel/sympde/issues"
Repository = "https://github.com/pyccel/sympde"

[tool.setuptools.packages.find]
include = ["sympde*"]
namespaces = false

[tool.setuptools.package-data]
"*" = ["README.rst"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = ["--strict-markers"]
python_files = ["test_*.py"]
python_classes = []
python_functions = ["test_*"]

[tool.coverage.run]
branch = true
source = ["sympde"]
omit = ["*/tests/*"]

[tool.coverage.report]
ignore_errors = true
exclude_also = [
    "def __repr__",
    "if self\\.debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "if False:",
    "if __name__ == .__main__.:",
    "@(abc\\.)?abstractmethod",
]
