"""Public user-facing API for SymPDE.

Objects are imported from the modules that define them instead of relying on
the wildcard re-exports in the package initializers.  This module is the one
supported location for convenient, flat imports such as::

    from sympde.api import BilinearForm, Square, elements_of, grad

Internal SymPDE code should continue to import objects from their defining
modules to keep its dependencies explicit.
"""

from sympde.version import __version__

from sympde.core.basic import Constant

from sympde.calculus.core import (
    Average,
    BasicOperator,
    BasicOperatorAdd,
    Bracket,
    Convect,
    Convolution,
    Cross,
    Curl,
    D,
    DiffOperator,
    Div,
    Dn,
    Dot,
    Grad,
    Hessian,
    Inner,
    Jump,
    Laplace,
    MinusInterfaceOperator,
    NormalDerivative,
    Outer,
    PlusInterfaceOperator,
    Rot,
    StrainTensor,
    add_basicop,
    avg,
    bracket,
    conv,
    convect,
    cross,
    curl,
    div,
    dot,
    grad,
    has,
    hessian,
    inner,
    is_constant,
    is_scalar,
    is_zero,
    jump,
    laplace,
    minus,
    outer,
    plus,
    rot,
)
from sympde.calculus.errors import ArgumentTypeError, CalculusError
from sympde.calculus.matrices import (
    Inverse,
    MatrixElement,
    MatrixSymbolicExpr,
    SymbolicDeterminant,
    SymbolicTrace,
    Transpose,
)

from sympde.topology.basic import (
    BasicDomain,
    Boundary,
    Connectivity,
    CornerBoundary,
    CornerInterface,
    Edge,
    Interface,
    InteriorDomain,
    Interval,
    ProductDomain,
    Union,
)
from sympde.topology.domain import (
    Area,
    BoundaryVector,
    Cube,
    Domain,
    ElementDomain,
    Line,
    MinusNormalVector,
    NCube,
    NCubeInterior,
    NormalVector,
    PeriodicDomain,
    PlusNormalVector,
    Square,
    TangentVector,
    split,
)
from sympde.topology.mapping import (
    BasicCallableMapping,
    Contravariant,
    Covariant,
    InterfaceMapping,
    InverseMapping,
    Jacobian,
    JacobianInverseSymbol,
    JacobianSymbol,
    LogicalExpr,
    MappedDomain,
    Mapping,
    MappingApplication,
    MultiPatchMapping,
    PullBack as MappingPullBack,
    SymbolicExpr,
    SymbolicWeightedVolume,
    get_logical_test_function,
)
from sympde.topology.space import (
    BasicFunctionSpace,
    Derham,
    IndexedVectorFunction,
    ProductSpace,
    Projection,
    Projector,
    ScalarFunction,
    ScalarFunctionSpace,
    TestFunction,
    Trace,
    VectorFunction,
    VectorFunctionSpace,
    element_of,
    elements_of,
    trace_0,
    trace_1,
)
from sympde.topology.derivatives import (
    DifferentialOperator,
    dx,
    dx1,
    dx2,
    dx3,
    dy,
    dz,
    find_partial_derivatives,
    get_atom_derivatives,
    get_atom_logical_derivatives,
    get_index_derivatives,
    get_index_derivatives_atom,
    get_index_logical_derivatives,
    get_index_logical_derivatives_atom,
    get_max_logical_partial_derivatives,
    get_max_partial_derivatives,
    get_number_derivatives,
    sort_partial_derivatives,
)
from sympde.topology.datatype import (
    H1Regularity,
    H1RegularityType,
    H1Space,
    H1SpaceType,
    HcurlRegularity,
    HcurlRegularityType,
    HcurlSpace,
    HcurlSpaceType,
    HdivRegularity,
    HdivRegularityType,
    HdivSpace,
    HdivSpaceType,
    L2Regularity,
    L2RegularityType,
    L2Space,
    L2SpaceType,
    RegularityType,
    SpaceType,
    UndefinedSpace,
    UndefinedSpaceType,
)
from sympde.topology.analytical_mapping import (
    AffineMapping,
    CollelaMapping2D,
    CzarnyMapping,
    IdentityMapping,
    PolarMapping,
    SphericalMapping,
    TargetMapping,
    TorusMapping,
    TorusSurfaceMapping,
    TwistedTargetMapping,
    TwistedTargetSurfaceMapping,
)
from sympde.topology.callable_mapping import CallableMapping
from sympde.topology.measure import (
    BasicMeasure,
    CanonicalMeasure,
    CartesianMeasure,
    Measure,
)

from sympde.expr.basic import BasicExpr, BasicForm
from sympde.expr.equation import (
    Equation,
    EssentialBC,
    Mean,
    NewtonIteration,
    find,
)
from sympde.expr.errors import (
    UnconsistentArgumentsError,
    UnconsistentBCError,
    UnconsistentError,
    UnconsistentLhsError,
    UnconsistentLinearExpressionError,
    UnconsistentRhsError,
)
from sympde.expr.evaluation import (
    BoundaryExpression,
    DomainExpression,
    InterfaceExpression,
    KernelExpression,
    TensorExpr,
    TerminalExpr,
)
from sympde.expr.expr import (
    BilinearForm,
    Functional,
    IntAdd,
    Integral,
    LinearExpr,
    LinearForm,
    Norm,
    SemiNorm,
    integral,
    is_linear_expression,
    linearize,
)

from sympde.exterior.calculus import (
    Adjoint,
    AdjointExteriorDerivative,
    AdjointInteriorProduct,
    AdjointLieDerivative,
    ExteriorDerivative,
    ExteriorProduct,
    Hodge,
    InteriorProduct,
    Ld,
    LieDerivative,
    PullBack,
    d,
    delta,
    hodge,
    ip,
    jp,
    ld,
    wedge,
)
from sympde.exterior.compiler import ExteriorCalculusExpr, augmented_expression
from sympde.exterior.datatype import (
    FiveForm,
    FiveFormType,
    FormType,
    FourForm,
    FourFormType,
    OneForm,
    OneFormType,
    SixForm,
    SixFormType,
    ThreeForm,
    ThreeFormType,
    TwoForm,
    TwoFormType,
    ZeroForm,
    ZeroFormType,
)
from sympde.exterior.form import DifferentialForm
from sympde.exterior.inference import infere_type

from sympde.printing.latex import LatexPrinter, latex
from sympde.utilities.utils import lambdify_sympde, plot_domain

# ``PullBack`` historically referred to the exterior-calculus operator in the
# root namespace.  Keep that spelling and provide explicit aliases for both
# otherwise-colliding pull-back concepts.
ExteriorPullBack = PullBack

__all__ = (
    '__version__',
    'Constant',
    # Calculus
    'Average',
    'BasicOperator',
    'BasicOperatorAdd',
    'Bracket',
    'Convect',
    'Convolution',
    'Cross',
    'Curl',
    'D',
    'DiffOperator',
    'Div',
    'Dn',
    'Dot',
    'Grad',
    'Hessian',
    'Inner',
    'Jump',
    'Laplace',
    'MinusInterfaceOperator',
    'NormalDerivative',
    'Outer',
    'PlusInterfaceOperator',
    'Rot',
    'StrainTensor',
    'add_basicop',
    'avg',
    'bracket',
    'conv',
    'convect',
    'cross',
    'curl',
    'div',
    'dot',
    'grad',
    'has',
    'hessian',
    'inner',
    'is_constant',
    'is_scalar',
    'is_zero',
    'jump',
    'laplace',
    'minus',
    'outer',
    'plus',
    'rot',
    'ArgumentTypeError',
    'CalculusError',
    'Inverse',
    'MatrixElement',
    'MatrixSymbolicExpr',
    'SymbolicDeterminant',
    'SymbolicTrace',
    'Transpose',
    # Topology
    'BasicDomain',
    'Boundary',
    'Connectivity',
    'CornerBoundary',
    'CornerInterface',
    'Edge',
    'Interface',
    'InteriorDomain',
    'Interval',
    'ProductDomain',
    'Union',
    'Area',
    'BoundaryVector',
    'Cube',
    'Domain',
    'ElementDomain',
    'Line',
    'MinusNormalVector',
    'NCube',
    'NCubeInterior',
    'NormalVector',
    'PeriodicDomain',
    'PlusNormalVector',
    'Square',
    'TangentVector',
    'split',
    'BasicCallableMapping',
    'Contravariant',
    'Covariant',
    'InterfaceMapping',
    'InverseMapping',
    'Jacobian',
    'JacobianInverseSymbol',
    'JacobianSymbol',
    'LogicalExpr',
    'MappedDomain',
    'Mapping',
    'MappingApplication',
    'MappingPullBack',
    'MultiPatchMapping',
    'SymbolicExpr',
    'SymbolicWeightedVolume',
    'get_logical_test_function',
    'BasicFunctionSpace',
    'Derham',
    'IndexedVectorFunction',
    'ProductSpace',
    'Projection',
    'Projector',
    'ScalarFunction',
    'ScalarFunctionSpace',
    'TestFunction',
    'Trace',
    'VectorFunction',
    'VectorFunctionSpace',
    'element_of',
    'elements_of',
    'trace_0',
    'trace_1',
    'DifferentialOperator',
    'dx',
    'dx1',
    'dx2',
    'dx3',
    'dy',
    'dz',
    'find_partial_derivatives',
    'get_atom_derivatives',
    'get_atom_logical_derivatives',
    'get_index_derivatives',
    'get_index_derivatives_atom',
    'get_index_logical_derivatives',
    'get_index_logical_derivatives_atom',
    'get_max_logical_partial_derivatives',
    'get_max_partial_derivatives',
    'get_number_derivatives',
    'sort_partial_derivatives',
    'H1Regularity',
    'H1RegularityType',
    'H1Space',
    'H1SpaceType',
    'HcurlRegularity',
    'HcurlRegularityType',
    'HcurlSpace',
    'HcurlSpaceType',
    'HdivRegularity',
    'HdivRegularityType',
    'HdivSpace',
    'HdivSpaceType',
    'L2Regularity',
    'L2RegularityType',
    'L2Space',
    'L2SpaceType',
    'RegularityType',
    'SpaceType',
    'UndefinedSpace',
    'UndefinedSpaceType',
    'AffineMapping',
    'CollelaMapping2D',
    'CzarnyMapping',
    'IdentityMapping',
    'PolarMapping',
    'SphericalMapping',
    'TargetMapping',
    'TorusMapping',
    'TorusSurfaceMapping',
    'TwistedTargetMapping',
    'TwistedTargetSurfaceMapping',
    'CallableMapping',
    'BasicMeasure',
    'CanonicalMeasure',
    'CartesianMeasure',
    'Measure',
    # Expressions
    'BasicExpr',
    'BasicForm',
    'Equation',
    'EssentialBC',
    'Mean',
    'NewtonIteration',
    'find',
    'UnconsistentArgumentsError',
    'UnconsistentBCError',
    'UnconsistentError',
    'UnconsistentLhsError',
    'UnconsistentLinearExpressionError',
    'UnconsistentRhsError',
    'BoundaryExpression',
    'DomainExpression',
    'InterfaceExpression',
    'KernelExpression',
    'TensorExpr',
    'TerminalExpr',
    'BilinearForm',
    'Functional',
    'IntAdd',
    'Integral',
    'LinearExpr',
    'LinearForm',
    'Norm',
    'SemiNorm',
    'integral',
    'is_linear_expression',
    'linearize',
    # Exterior calculus
    'Adjoint',
    'AdjointExteriorDerivative',
    'AdjointInteriorProduct',
    'AdjointLieDerivative',
    'ExteriorDerivative',
    'ExteriorProduct',
    'ExteriorPullBack',
    'Hodge',
    'InteriorProduct',
    'Ld',
    'LieDerivative',
    'PullBack',
    'd',
    'delta',
    'hodge',
    'ip',
    'jp',
    'ld',
    'wedge',
    'ExteriorCalculusExpr',
    'augmented_expression',
    'FiveForm',
    'FiveFormType',
    'FormType',
    'FourForm',
    'FourFormType',
    'OneForm',
    'OneFormType',
    'SixForm',
    'SixFormType',
    'ThreeForm',
    'ThreeFormType',
    'TwoForm',
    'TwoFormType',
    'ZeroForm',
    'ZeroFormType',
    'DifferentialForm',
    'infere_type',
    # Output and utilities
    'LatexPrinter',
    'latex',
    'lambdify_sympde',
    'plot_domain',
)
